version: 0.2
env:
  variables:
    PROFILE: dev
    Stage: dev
    CACHE_CONTROL: "86400"
    JAVA_OPTS: "-Djdk.tls.client.protocols=TLSv1.2 -Dhttps.protocols=TLSv1.2 -Xmx2048m -Xms512m"
    NODE_OPTIONS: "--max_old_space_size=4096"
    PROJECTKEY: "psg-event-ingestion"

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - export M2_HOME=/opt/maven
      - export PATH=${M2_HOME}/bin:${PATH}
      - aws --version
      - java --version
      - aws ssm put-parameter --name /application/infomart/$Stage/export/s3-bucket --value